### ISSUE TITLE
RE: Echo Dot/Echo/Tap?

### ISSUE THREAD

**Issue by ghost** [josephdouce/Alexa-IFTTT-UK#1]
In our article on hackster.io you mentioned in the requirements that an amazon alexa tap is required. Will this work around still work on the echo dot 2 or the Echo?

**Comment by josephdouce** [comment]
It will work with any of the 3 only 1 required Tap or Echo or Dot. hackster.io updated accordingly.

**Comment by eversonl** [comment]
the 'Handler' in the configuration needs to be set correctly
While creating the lambda function it will ask for Lambda function handler. You have to name it as your Python_File_Name.Method_Name. In this scenario I named it as lambda.lambda_handler (lambda.py is the file name)
