### ISSUE TITLE
 "errorMessage": "Unable to import module 'lambda_function'"

### ISSUE THREAD

**Issue by eversonl** [josephdouce/Alexa-IFTTT-UK#2]
Hi, I was getting the error:-
Unable to import module 'lambda_function': No module named lambda_function

While creating the lambda function it will ask for Lambda function handler. You have to name it as your Python_File_Name.Method_Name. In this scenario I named it as lambda.lambda_handler (lambda.py is the file name)

**Comment by josephdouce** [comment]
I updated naming convention to lambda.py for the main file so handler is lambda.lambda_handler now.
